spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      #//-与classpath 之间有空格
      schema: 
        - classpath:database/schema.sql 
 #       - classpath:database/import.sql
      continue-on-error: false
      initialization-mode: always
      sql-script-encoding: utf-8

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.abigfish.shiro.config.MySQL5DialectUTF8

    thymeleaf:
       cache: false
       mode: LEGACYHTML5