spring:
  application:
    name: springboot-mqtt
  servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 10MB
server:
  port: 8080
  
mqtt:
  url: tcp://192.168.0.112:1884
  username: admin
  password: 123
  clientId: client-01
  defaultTopic: default_topic