spring:
    activemq:
      user: admin
      password: admin
      broker-url: tcp://192.168.0.7:61616
      pool:
        enabled: true
        max-connections: 50
      packages:
        trust-all: true

